
### OA测试登录
post http://oa.gzqiaoyin.com/login/Login.jsp
Content-Type: application/x-www-form-urlencoded

loginid=00119960
&userpassword=1qaz@WSX

### OA测试登录
post https://oa.gzqiaoyin.com/wui/theme/ecology8/page/login.jsp?templateId=3&logintype=1&gopage=
Content-Type: multipart/form-data boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW  

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"




###
post http://192.168.1.144/vhost/custom/api_stock.php
?fcname=get_allkind_increased
&code=day5

###
post https://gd.122.gov.cn/user/m/uservio/suriquery
Content-Type: multipart/form-data  

 startDate: "20210101",
        endDate: "20211001",
        hpzl: "02",
        hphm: "粤A29BN9",
        page: "1",
        type:"0"

### 企业微信获取token
post https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=wwd8658d118708a9ae&corpsecret=_toJoCPz-jx-npE8IW7sucyehx4feQT8jFYfYXbF_Cc


### 企业微信获取token 2
post https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=wwd8658d118708a9ae&secret=_toJoCPz-jx-npE8IW7sucyehx4feQT8jFYfYXbF_Cc


### 企业微信发送消息
post https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=Os69A8PfXeom6gDxGaStGYiSnivMti_ftT3l_69h2navyoYBqWv2ce7SacWb-YELdM5YKCme_Sog4VGP6_uDXRyueqhfJWBxhDnsLDf6Ry39iMP5F17aG9wuPyLCrILGYSczF7l7ENesZ13RYAmgq2k3dWMGAZvPBKV92CGUUV8qWab9xCc28jaS9d8X23NX9x0LMl5uLMDiJXjlKZ3fPA
Content-Type: multipart/json

{"touser" : "FanBingQi","msgtype" : "text",   "agentid" : 1000003,   "text" : {       "content" : "ag3"   },   "safe":0,   "enable_id_trans": 0,   "enable_duplicate_check": 0,   "duplicate_check_interval": 1800}

### 模拟提交微信测试接口 -- 文本 Content-Type:application/json 和  multipart/json
post http://127.0.0.1:8080/send_wx?UID=1q1qq
Content-Type: multipart/json

{"touser" : "FanBingQi","msgtype" : "text", "text" :"tst22", "agentid":1000003,"UID" : "BF4E3603-135C-48F1-9DBB-479A6FD5BBF8" }

### 模拟提交微信测试接口 -- 图片
post http://127.0.0.1:8080/up_file
Content-Type: multipart/json

{"type":"image","filePath" :"./te3.png"}

### 获取微信部门的人员
post https://qyapi.weixin.qq.com/cgi-bin/user/simplelist?access_token=wcsDwVASjOYnxbL0GVdEcPkkERqPKCpplztb-hEihC3oMCMedTJmHWUrzhk_Can4mK4QwfIYr_PeishItNBuSXd-hKTi9LZ0rh_zDZC6kFQSdd3GFGWSPeEaMAbp5oaWgnvHSQueXgHOaNbsxM5VuyV6OHuaRCGmE4uqDSsGwW767HB3bn_p3hQveOwHpFIzRZO_MJBt_Gx-5eDrE7unDA&department_id=1&fetch_child=1

###
POST https://t.10jqka.com.cn/newcircle/group/modifySelfStock/?callback=modifyStock&op=add&stockcode=000006&_=1654498860393

### 东方财富自选股接口测试
GET http://myfavor.eastmoney.com/v4/webouter/as?appkey=d41d8cd98f00b204e9800998ecf8427e&cb=jQuery33103190186058732998_1654581252736&g=1&sc=0%24000968&_=1654581252879 
cookie:em_hq_fls=js
cookie:st_si=42671117262218
cookie:qgqp_b_id=0e771b8aa1190285582a8b6ca7938de3
cookie:em-quote-version=topspeed
cookie:p_origin=https%3A%2F%2Fpassport2.eastmoney.com
cookie:login_canskip=true
cookie:intellpositionL=1013.49px
cookie:yzmkey=92928e5dd2f6496d8c4e0bfd27244fd9
cookie:intellpositionT=2055.11px
cookie:login_apicontext=rhz3Y1cR5uZ5IpDRpN%2FVmj1YGOmoCLLbecJT8AcRdWX61DjNP4rk%2B3uQUHM%2FVssl912coOF61EmqPYD0TxzOcOCh0NCx6evgBgZIwBhV7aH7i5pHbspEXd09o6fjskxt%2Fe0jaO4N4YDKsFZcWTv7r5vm9dKWkBN5s3FUB1OgCB4%3D
cookie:mtp=1
cookie:ct=iYyz_fsnhBJb6GTebXeRKIbp3DRCpeodZAja2AJFXE0TRbzaa903yDrnyL9Wsf6TmmjAygqq2kBRulEDF-w3RE_xyPI_yyTqUb0Gtk1hAB6x4KTBbLF_Xgp7oo4n4xusU4qTJY1sqPxSBbWmMUdNWJg2OjGmc7w4xOfh5lF_-yM
cookie:ut=FobyicMgeV6W21ICVIh674b-4cT8YBaIDxfxf5hBLhgiiVlkCdk9OEyAaXgBfZQYi7vu62r2eFFB1RiQVSLTvluK0U_DUIOYwG1lUr-h75-z1opMZyrowt3ntpcCpmDBuzkbs-2e0d7G0DJpQDrI3WN51gbJfaxI-2p5AuYnzmBCc3jtHBCxEmSNE-_4zB19iyxCNDTfRDAp9lew4x7rg8K5ctGVmM5DPUmc47u04rAgydxorKLx6iW72zueQCFTp9X5q_Aqkdy9yQtUf2QaWeJe16t_yxOb
cookie:pi=3391013824560020%3b%3b%e5%bf%83__%e8%bf%9c%3bFbwEroScrhAnlsmh8HdQLplIvLP6bt9LkoQlyhp%2bSDAbF5FEV9wswCQIAiH8HZuxJgaNAcpIUKZwA8LE7%2b1wAuzndSZSRRyZ%2fdGGljUID0xJFyYrlPI%2fbvpkZgv3Rq0PVumRzY32UtIA3Q2uKO6jbQx0%2bc0o3JNbVMc9RkaFx37l06ky7Qh4OhsPfICbg7ZfQZ1lVoHq%3bCwuhWhkwM5j3ec%2b60V4fY%2fit9Q5J5fXrwZutDuwsqHQFFg1LVpl%2f%2fLa%2fYgIk2eWWl5dXBIYOSFRHrFT2dn%2fmzHxwWtxtZgHHVbkXJYGPVJ9EWis49T9bHXbzxfJeA%2f2BlaYDZZddeLRHGszG0YLHZM3ZKPXPOg%3d%3d
cookie:uidal=3391013824560020%e5%bf%83__%e8%bf%9c
cookie:sid=8960218
cookie:vtpst=|
cookie:HAList=a-sh-601975-%u62DB%u5546%u5357%u6CB9%2Ca-sz-000756-%u65B0%u534E%u5236%u836F%2Ca-sz-000957-%u4E2D%u901A%u5BA2%u8F66%2Ca-sz-002761-%u6D59%u6C5F%u5EFA%u6295%2Ca-sh-601066-%u4E2D%u4FE1%u5EFA%u6295%2Ca-sz-000722-%u6E56%u5357%u53D1%u5C55%2Ca-sz-002883-%u4E2D%u8BBE%u80A1%u4EFD%2Cty-90-BK0473-%u8BC1%u5238%2Ca-sz-002670-%u56FD%u76DB%u91D1%u63A7%2Ca-sz-002603-%u4EE5%u5CAD%u836F%u4E1A%2Ca-sz-002424-%u8D35%u5DDE%u767E%u7075%2Ca-sh-600062-%u534E%u6DA6%u53CC%u9E64
cookie:st_pvi=18891856310866
cookie:st_sp=2021-12-15%2009%3A14%3A12
cookie:st_inirUrl=http%3A%2F%2Fquote.eastmoney.com%2Fsz300967.html
cookie:st_sn=7084
cookie:st_psi=20220607154620191-113200301712-2515579100
cookie:st_asi=20220607154620191-113200301712-2515579100-Web_so_ss-3
Referer: http://quote.eastmoney.com/